### ISSUE TITLE
Its not an issue but a question.

### ISSUE THREAD

**Issue by danilocecilia** [eveporcello/color-organizer#1]
What are these signs "!" doing on your graqhql scripts? like : allColors: [Color!]!

**Comment by eveporcello** [comment]
It means that the value is non-nullable - i.e. if I query the `allColors` field, `allColors` must return a non-nullable list of non-nullable color objects. 

This is a good article about this topic: https://blog.apollographql.com/using-nullability-in-graphql-2254f84c4ed7

Thanks for the question!
